package cat.foixench.ceina.contentprovider.activity;

import android.app.LoaderManager;
import android.content.Context;
import android.content.CursorLoader;
import android.content.Loader;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.CursorAdapter;
import android.widget.ListView;
import android.widget.SimpleCursorAdapter;

import cat.foixench.ceina.contentprovider.R;
import cat.foixench.ceina.contentprovider.db.ClientesDBContract;
import cat.foixench.ceina.contentprovider.provider.ClientesProvider;
import cat.foixench.ceina.contentprovider.util.AppUtils;


/**
 * Created by llorenc on 23/10/2017.
 */

public class MainActivity extends AppCompatActivity implements LoaderManager.LoaderCallbacks{

    ListView lvClientes;
    SimpleCursorAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_activity_layout);

        lvClientes = (ListView) findViewById(R.id.lvClientes);

        // llamamos al loader
        getLoaderManager().initLoader(AppUtils.CLIENT_LOADER_ID, null, this);

    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     * @param id   The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    @Override
    public Loader onCreateLoader(int id, Bundle args) {
        String [] projection = new String [] {ClientesDBContract._ID, ClientesDBContract.COL_NOMBRE, ClientesDBContract.COL_EMAIL, ClientesDBContract.COL_TELEFONO};
        String selection = null;
        String [] selectionArgs = null;
        String sortOrder = null;

        Uri clientesUri = ClientesProvider.CONTENT_URI;
        CursorLoader cursorLoader = new CursorLoader(this, clientesUri, projection, selection, selectionArgs, sortOrder);

        return cursorLoader;
    }

    /**
     *
     * @param loader The Loader that has finished.
     * @param data   The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader loader, Object data) {

        Cursor cursor = (Cursor) data;

        cursor.moveToFirst();

        String [] from = new String [] {ClientesDBContract.COL_NOMBRE, ClientesDBContract.COL_TELEFONO, ClientesDBContract.COL_EMAIL};
        int [] to = new int [] {R.id.tvClienteNombre, R.id.tvClienteTelefono, R.id.tvClienteEmail};

        adapter = new SimpleCursorAdapter(this, R.layout.clientes_list_item, cursor, from, to, 0);

        lvClientes.setAdapter(adapter);

    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader loader) {

    }
}
